export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_POLL_TYPE = "SET_POLL_TYPE";
export const SET_SESSION_UUID = "SET_SESSION_UUID";
export const SET_SESSION_NAME = "SET_SESSION_NAME";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_POLLS = "SET_POLLS;"
export const SET_POLL_TYPES_LIST = "SET_POLL_TYPES_LIST";
